import { Inter, Poppins } from 'next/font/google'
import './globals.css'
import {Providers} from "./providers";
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight:['400'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
        <body className={poppins.className}>
      <Providers>
        {children}
        <Analytics />
      </Providers>
      </body>
      {/* <body className={concert_One.className}>{children}</body> */}
    </html>
  )
}
